// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigPath() {
  return window['go']['main']['App']['ConfigPath']();
}

export function ConnectClient(arg1) {
  return window['go']['main']['App']['ConnectClient'](arg1);
}

export function DisconnectClient(arg1) {
  return window['go']['main']['App']['DisconnectClient'](arg1);
}

export function DiscoverClients() {
  return window['go']['main']['App']['DiscoverClients']();
}

export function DiscoverMCPServers() {
  return window['go']['main']['App']['DiscoverMCPServers']();
}

export function DiscoverMCPServersForClients(arg1) {
  return window['go']['main']['App']['DiscoverMCPServersForClients'](arg1);
}

export function DiscoverSkillsForClients(arg1) {
  return window['go']['main']['App']['DiscoverSkillsForClients'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConnectedClientIDs() {
  return window['go']['main']['App']['GetConnectedClientIDs']();
}

export function IntrospectMCPServer(arg1) {
  return window['go']['main']['App']['IntrospectMCPServer'](arg1);
}
