// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {discovery} from '../models';

export function ConfigPath():Promise<string>;

export function ConnectClient(arg1:string):Promise<config.AppConfig>;

export function DisconnectClient(arg1:string):Promise<config.AppConfig>;

export function DiscoverClients():Promise<Array<discovery.ClientInfo>>;

export function DiscoverMCPServers():Promise<Array<discovery.MCPServer>>;

export function DiscoverMCPServersForClients(arg1:Array<string>):Promise<Array<discovery.MCPServer>>;

export function DiscoverSkillsForClients(arg1:Array<string>):Promise<Array<discovery.SkillAsset>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetConnectedClientIDs():Promise<Array<string>>;

export function IntrospectMCPServer(arg1:discovery.MCPServer):Promise<discovery.MCPServer>;

export function RescanAgents():Promise<Array<config.AgentConfig>>;
